Repository event-information/SeoulCulturePort-Backend, pull requests merged in 2023-03, with the labels that each got.

#15 1 회원가입 구현
  .idea/dataSources.xml
  SeoulCulturePort/.gitignore
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/config/WebSecurityConfig.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/UserController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CheckIdRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CheckIdResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/LoginRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/SignupRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/StatusEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/UserRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/UserService.java
  SeoulCulturePort/src/main/resources/application.properties
Labels: bug

#20 12-상세페이지-댓글-수정
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CommentRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CommentResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/Board.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/Comment.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/CommentRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/CommentService.java
Labels: enhancement

#21 13-상세페이지-댓글-삭제
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/StatusResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/CommentRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/CommentService.java
Labels: enhancement

#22 fix: cors해결
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/config/WebSecurityConfig.java
Labels: bug

#27 24-회원정보-닉네임-수정
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/UserController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/PatchNickRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/User.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/UserService.java
Labels: enhancement

#28 feat: 비밀번호 수정 기능 추가, 로그인 반환 값 닉네임 추가
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/UserController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CheckIdRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/LoginRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/LoginResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/ModifyPwRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/SignupRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/User.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/UserService.java
Labels: bug, enhancement

#29 v1.0 릴리스 시작
  .idea/compiler.xml
  .idea/dataSources.xml
  .idea/git_toolbox_prj.xml
  .idea/uiDesigner.xml
  SeoulCulturePort/.gitignore
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/SeoulCulturePortApplication.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/config/WebSecurityConfig.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/BoardController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/CommentController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/controller/UserController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/BoardDetailResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/BoardListResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/BoardRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/BoardSimpleResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CheckIdRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CheckIdResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CommentRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/CommentResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/LoginRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/LoginResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/MessageResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/ModifyPwRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/PatchNickRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/SecurityExceptionDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/SignupRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/StatusEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/StatusResponseDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/dto/UserRequestDto.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/Board.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/Comment.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/Timestamped.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/entity/User.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ApiException.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ApiExceptionController.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ErrorResult.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/jwt/JwtAuthFilter.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/jwt/JwtUtil.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/jwt/UserRoleEnum.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/BoardRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/CommentRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/repository/UserRepository.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/security/CustomAccessDeniedHandler.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/security/CustomAuthenticationEntryPoint.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/security/UserDetailsImpl.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/security/UserDetailsServiceImpl.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/BoardService.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/CommentService.java
  SeoulCulturePort/src/main/java/com/example/seoulcultureport/service/UserService.java
  SeoulCulturePort/src/main/resources/application.properties
Labels: enhancement

#36 닉네임 중복처리 기능구현
  src/main/java/com/example/seoulcultureport/config/WebSecurityConfig.java
  src/main/java/com/example/seoulcultureport/controller/UserController.java
  src/main/java/com/example/seoulcultureport/dto/CheckNickRequestDto.java
  src/main/java/com/example/seoulcultureport/dto/CheckNickResponseDto.java
  src/main/java/com/example/seoulcultureport/service/UserService.java
Labels: enhancement

#42 댓글 좋아요 기능 구현
  src/main/java/com/example/seoulcultureport/controller/CommentController.java
  src/main/java/com/example/seoulcultureport/dto/CommentResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/StatusResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupStatus.java
  src/main/java/com/example/seoulcultureport/entity/Comment.java
  src/main/java/com/example/seoulcultureport/entity/Thumbsup.java
  src/main/java/com/example/seoulcultureport/entity/User.java
  src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  src/main/java/com/example/seoulcultureport/repository/ThumbsupRepository.java
  src/main/java/com/example/seoulcultureport/service/CommentService.java
Labels: enhancement

#47 좋아요, 비밀번호 확인 수정
  src/main/java/com/example/seoulcultureport/controller/BoardController.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardDetailResponseDto.java
  src/main/java/com/example/seoulcultureport/entity/Board.java
  src/main/java/com/example/seoulcultureport/entity/Thumbsup.java
  src/main/java/com/example/seoulcultureport/exception/ExceptionEnum.java
  src/main/java/com/example/seoulcultureport/repository/ThumbsupRepository.java
  src/main/java/com/example/seoulcultureport/service/BoardService.java
  src/main/java/com/example/seoulcultureport/service/UserService.java
Labels: bug

#50 댓글 좋아요 코드 픽스
  src/main/java/com/example/seoulcultureport/controller/BoardController.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardDetailResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/commentDto/CommentResponseDto.java
  src/main/java/com/example/seoulcultureport/entity/Board.java
  src/main/java/com/example/seoulcultureport/entity/Comment.java
  src/main/java/com/example/seoulcultureport/service/BoardService.java
  src/main/java/com/example/seoulcultureport/service/UserService.java
Labels: enhancement

#52 fix: 메인게시판 좋아요 개수 추가, 상세페이지 좋아요 개수 추가
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardListResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardSimpleResponseDto.java
Labels: bug

#53 게시물 좋아요, 댓글좋아요 진혁님꺼랑 합체
  src/main/java/com/example/seoulcultureport/controller/BoardController.java
  src/main/java/com/example/seoulcultureport/controller/CommentController.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupStatus.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardDetailResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/commentDto/CommentResponseDto.java
  src/main/java/com/example/seoulcultureport/entity/Board.java
  src/main/java/com/example/seoulcultureport/entity/BoardLike.java
  src/main/java/com/example/seoulcultureport/entity/Comment.java
  src/main/java/com/example/seoulcultureport/entity/CommentLike.java
  src/main/java/com/example/seoulcultureport/entity/User.java
  src/main/java/com/example/seoulcultureport/repository/BoardLikeRepository.java
  src/main/java/com/example/seoulcultureport/repository/CommentLikeRepository.java
  src/main/java/com/example/seoulcultureport/repository/ThumbsupRepository.java
  src/main/java/com/example/seoulcultureport/service/BoardService.java
  src/main/java/com/example/seoulcultureport/service/CommentService.java
Labels: enhancement

#54 좋아요 main으로 merge
  src/main/java/com/example/seoulcultureport/controller/BoardController.java
  src/main/java/com/example/seoulcultureport/controller/CommentController.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/ThumbsupStatus.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardDetailResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardListResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardRequestDto.java
  src/main/java/com/example/seoulcultureport/dto/boardDto/BoardSimpleResponseDto.java
  src/main/java/com/example/seoulcultureport/dto/commentDto/CommentResponseDto.java
  src/main/java/com/example/seoulcultureport/entity/Board.java
  src/main/java/com/example/seoulcultureport/entity/BoardLike.java
  src/main/java/com/example/seoulcultureport/entity/Comment.java
  src/main/java/com/example/seoulcultureport/entity/CommentLike.java
  src/main/java/com/example/seoulcultureport/entity/User.java
  src/main/java/com/example/seoulcultureport/repository/BoardLikeRepository.java
  src/main/java/com/example/seoulcultureport/repository/CommentLikeRepository.java
  src/main/java/com/example/seoulcultureport/repository/ThumbsupRepository.java
  src/main/java/com/example/seoulcultureport/service/BoardService.java
  src/main/java/com/example/seoulcultureport/service/CommentService.java
Labels: bug, enhancement
